### PR TITLE
Updated annotating and submitting metadata section

### PR DESCRIPTION
**Pull request by ychae**

### CODE REVIEW

**Comment by ychae** [comment]
@milen-sage I tried to add you as a reviewer to this but it looks like I don't have enough permissions to add in reviewers

**Comment by milen-sage** [comment]
@ychae feel free to merge :)

**Comment by ychae** [comment]
Thanks @milen-sage! I also seem to be lacking merge permissions 😭 Would you be able to merge?

**Comment by ychae** [comment]
👍🏻

**Comment by milen-sage** [comment]
I think permissions should be fixed now for this repo in ncihtan. I'll check tomorrow if I can add you to a team that has permissions throughout the ncihtan organization.

**Pull request merged**
